name: learners_1
description: leaener's 1.0


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  floating_bottom_navigation_bar: ^1.4.1
  flutter_screenutil: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Product-Sans-Thin.ttf
          weight: 200
